kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: pvc-{{ template "charts.fullname" . }}
  labels:
    app: {{ template "charts.fullname" . }}
    chart: {{ template "charts.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 2Gi
  storageClassName: nfs-ssd
