# Default values for charts.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 2

hpa:
  minReplicas: 1
  maxReplicas: 3
    
image:
  pullPolicy: IfNotPresent

service:
  type: ClusterIP
  port: 8080

ingress:
  enabled: true
  annotations: {}
  path: /

resources:
  limits:
    cpu: "2"
    memory: "4Gi"
  requests:
    cpu: "2"
    memory: "3Gi"
 
serviceMonitor:   
  enabled: false 

int:   
  enabled: false
